erp/views.py
static/scss/style.scss
templates/erps/commune.html

[Trello card](https://trello.com/c/MqMsytws/201-permettre-au-champ-recherche-daller-sur-une-autre-ville-lorsque-je-suis-d%C3%A9j%C3%A0-sur-un-territoire)

Add a search scope selector.

---

Pipfile
Pipfile.lock
Procfile
README.md
erp/jobs/check_closed_erps.py
erp/management/commands/check_closed_erps.py
erp/management/commands/start_scheduler.py
erp/test/fixtures.py
erp/test/test_jobs.py

[Trello card](https://trello.com/c/gW0xidgq/221-%C3%A9crire-des-tests-pour-la-fonction-de-v%C3%A9rification-de-statut-dactivit%C3%A9-des-erp)

Refactor scheduled jobs handling, add tests

---

.github/workflows/codeql-analysis.yml

- https://github.blog/2020-09-30-code-scanning-is-now-available/
- https://docs.github.com/en/free-pro-team@latest/github/finding-security-vulnerabilities-and-errors-in-your-code/enabling-code-scanning-for-a-repository

Setup CodeQL analysis.

---

core/settings.py
templates/base.html

Experimental HTTP versioning of static assets.

Append timestamp as qs to static assets url.

---

erp/forms.py
erp/sirene.py
erp/views.py
templates/contrib/0-start.html
tests/erp/test_sirene.py

Add an optional NAF search field to Sirene lookup form.

---

erp/forms.py
templates/contrib/0-start.html

Implement city autocomplete in contrib erp lookup form.

---

erp/provider/entreprise.py
erp/views.py
tests/erp/test_contrib.py

[Trello card](https://trello.com/c/W65TXpMJ/324-exploiter-lapi-entreprise-opendata-pour-la-recherche-dun-siret)

Leverage entreprise api to search for siret info.

---

core/lib/diff.py
core/lib/sql.py
core/lib/text.py
erp/management/commands/create_user.py
erp/managers.py
erp/models.py
erp/provider/entreprise.py
erp/provider/public_erp.py
erp/provider/sirene.py
stats/views.py
tests/core/test_diff.py
tests/core/test_text.py

Trello card https://trello.com/c/lfHy2Bg0/338-cr%C3%A9er-un-module-coreutilstext-etc

Move disparate helpers to new core.lib module.

---

Pipfile
Pipfile.lock
core/settings.py
static/scss/style.scss
templates/common/matomo.html
templates/common/sentry.html
templates/compte/mes_erps.html
templates/contrib/0a-search_results.html
templates/contrib/1-admin-infos.html
templates/contrib/2-localisation.html
templates/contrib/9-labellisation.html
templates/contrib/base_access_form.html
templates/contrib/forms/public_erp_form.html
templates/contrib/forms/sirene_form.html
templates/erps/commune.html
templates/erps/commune/accessibilite.html
templates/erps/commune/erp.html
templates/erps/commune/fields.html
templates/index.html
templates/stats/index.html
templates/swagger-ui.html

Audit: https://observatory.mozilla.org/analyze/acceslibre.beta.gouv.fr
Ressources :
- https://infosec.mozilla.org/guidelines/web_security#content-security-policy
- https://django-csp.readthedocs.io/en/latest/nonce.html
- https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP

Implement Content Security Policy.

---

core/settings.py
core/sitemaps.py
core/urls.py
erp/managers.py

Docs: https://docs.djangoproject.com/en/3.1/ref/contrib/sitemaps/

Add sitemaps.

---

erp/forms.py
erp/templatetags/a4a.py
erp/urls.py
erp/views.py
templates/compte/base.html
templates/compte/index.html
templates/compte/mon_identifiant.html
tests/erp/test_compte.py
tests/erp/test_forms.py

Allow users to change their username.

---

core/mailer.py
erp/jobs/notify_changed_erps.py
erp/management/commands/start_scheduler.py
erp/versioning.py
templates/mail/changed_erp_notification.txt
tests/erp/test_notifs.py

[trello card](https://trello.com/c/9d6fovD1/283-en-tant-que-contributeur-je-veux-recevoir-des-notifications-par-email-quand-ma-fiche-est-modifi%C3%A9e-par-un-tiers)

Send notifications to erp owners when they're updated by others.

---

core/lib/text.py
erp/forms.py
erp/models.py
erp/provider/arrondissements.py
erp/provider/entreprise.py
erp/provider/opendatasoft.py
erp/provider/public_erp.py
erp/provider/search.py
erp/templatetags/a4a.py
erp/views.py
templates/contrib/0a-search_results.html
tests/erp/provider/test_entreprise.py
tests/erp/provider/test_opendatasoft.py
tests/erp/provider/test_public_erp.py
tests/erp/provider/test_search.py
tests/erp/test_contrib.py

[Trello Card](https://trello.com/c/REHYHzzm/398-investiguer-api-sirene-opendatasoft)

Add ODS search provider.

---

erp/forms.py
erp/schema.py
templates/contrib/8-sanitaires.html
templates/erps/commune/fields.html
tests/erp/test_browser.py
tests/erp/test_notifs.py
tests/fixtures.py

[Trello card](https://trello.com/c/JtTBxEdt/249-modifformulaire-ajout-question-sanitaires)

Map sanitaires_adaptes count to bools in the ui.

---

erp/templatetags/a4a.py
erp/urls.py
erp/views.py
subscription/views.py
templates/compte/base.html
templates/compte/mes_abonnements.html
tests/erp/test_browser.py

[Trello card](https://trello.com/c/o2FqJ99P/431-ajouter-une-vue-mes-abonnements-dans-mon-compte-listant-les-%C3%A9tablissements-auxquels-lutilisateur-est-abonn%C3%A9)

Add a subscription management section in account admin.

---

erp/provider/opendatasoft.py
tests/erp/provider/test_opendatasoft.py

Trello card https://trello.com/c/2jgK9j7s/443-erreur-lors-du-formattage-de-la-raison-sociale-des-donn%C3%A9es-opendatasoft

Fix and improve ODS rep results formatting.

---

Pipfile
Pipfile.lock

Bump Django to 3.1.5 and lxml to 4.6.2.

---

static/img/logo-acceslibre.svg
templates/contrib/0a-search_results.html
tests/erp/test_drafts.py

[Trello card](https://trello.com/c/tk4gQ7gZ/439-reprise-dun-brouillon-de-mon-compte)
Allow a user to take over a draft right from the erp search results.

Allow users to find their drafts listed in erp search results.

---

static/js/index.js
static/js/jquery.js

Fix race condition with loading/using selectWoo.

---

README.md

Déplacement de parties du README trop longues ou moins utiles vers des articles wiki, afin d'alléger la lecture.
@n1k0 j'ai également modifié la procédure d'init de la database, dis-moi si c'est ok pour toi. J'ai testé avec docker-compose, mais pas avec psql directement parce que je l'ai pas installé, tu peux tester avec une copie du .sql ou tu renomme la database et l'user.

shorter README, moved to wiki

---

static/js/app.js
static/scss/style.scss

Add a right click context menu to add erp from map.

---

erp/urls.py
erp/views.py
templates/challenge/podium.html

Add a temporary DDT challenge podium page.

---

erp/views.py
templates/search/results.html

[Trello card](https://trello.com/c/M3pQ8rWC/501-etq-internaute-je-peux-localiser-un-r%C3%A9sultat-sur-la-carte)
https://user-images.githubusercontent.com/41547/107962408-c43d7080-6f5b-11eb-93f5-35c3dac6c5a0.mp4

Highlight searched map points

---

erp/forms.py

[Trello card](https://trello.com/c/C9biz1sT/579-bug-ui-inscription)

Improve username validation error messages.

---

erp/jobs/purge_accounts.py
erp/management/commands/purge_accounts.py
erp/management/commands/start_scheduler.py
tests/erp/test_jobs.py

[Trello card](https://trello.com/c/MsT7kEDp/580-limiter-linscription-des-bots#comment-605b73e85187b98897e99ab8)

Purge user accounts after 30 days without activation.

---

erp/managers.py
erp/schema.py
stats/views.py
templates/stats/index.html
tests/erp/test_managers.py
tests/stats/tests.py

Improve stats accuracy regarding erps filled with a11y data.

---

erp/views.py
templates/contrib/claim.html
templates/erps/commune/erp_actions.html
tests/erp/test_contrib.py

[Trello](https://trello.com/c/XBy5xNo5/566-attribuer-la-propri%C3%A9t%C3%A9-dun-erp-%C3%A0-son-gestionnaire-d%C3%A9clar%C3%A9-si-aucun-propri%C3%A9taire-pr%C3%A9c%C3%A9dent)

Add a claim button on erp details page.

---

templates/erps/commune/erp.html
templates/erps/commune/erp_actions.html
templates/erps/commune/erp_metas.html

Revamp ERP details page layout and information hierarchy.

---

stats/urls.py
stats/views.py
templates/stats/objectifs.html

Add a goal metrics page.

---

erp/jobs/import_centres_vaccination.py
erp/management/commands/start_scheduler.py

[Trello card](https://trello.com/c/kX5bSymA/599-importer-les-centres-de-vaccination-toutes-les-heures)

Import CV data every hour, avoid sending report emails.

---

erp/schema.py
erp/urls.py
erp/views.py
templates/contrib/documentation.html

Add page listing all a11y fields for humans.

---

erp/managers.py
erp/views.py
static/js/ui/SearchWhere.js
templates/search/results.html
tests/erp/test_browser.py

Sophie:
> Est ce normal qu'on puisse saisir autre chose que ce qui est proposé par l'autocomplete ?
> Ca me paraît poser pb car si je tape clichy, sans sélectionner dans l'autocomplete clichy (92), ça sort n'imp
@celiacheff:
> Et le point UX dont je t'ai parlé: si je tape "lyon" dans le where sans autocomplete et que je fait ma recherche, j'ai affiché comme recherche "lyon/boulangerie" mais en fait ça sera France entière.

Fix raw where search

---

static/js/ui/ConditionalForm.js

[Trello](https://trello.com/c/t784u7uy/634-modif-position-question-porte-vitr%C3%A9e)

Position question porte d'entree dans le formulaire

---

erp/export/static/schema.json
erp/schema.py
templates/contrib/5-exterieur.html
tests/erp/test_forms.py

[Trello](https://trello.com/c/2qxgHv5o/659-remplacer-le-terme-cheminement-par-chemin)

Modification des cheminements en chemins

---

.circleci/config.yml
erp/export/static/schema.json
erp/forms.py
erp/schema.py
static/scss/style.scss
templates/erp/includes/accessibilite.html
templates/erp/includes/fields.html
templates/erp/includes/history.html
tests/erp/test_forms.py
tests/erp/test_func.py

Trello: https://trello.com/c/pRI2eazJ/616-etq-internaute-je-consulte-la-liste-des-crit%C3%A8res-dun-erp

Render distinct specific phrasing for a11y presented fields.

---

compte/urls.py
compte/views.py
erp/templatetags/a4a.py
erp/urls.py
erp/views.py
templates/compte/base.html
templates/compte/mon_email.html
templates/compte/mon_email_sent.html
tests/compte/test_change_email.py
tests/contact/test_contact.py
tests/erp/test_browser.py

Migrate all account related code to the compte app.

---

erp/imports/mapper/gendarmerie.py
erp/imports/mapper/vaccination.py
erp/managers.py
erp/provider/search.py
tests/erp/imports/mapper/test_gendarmerie.py

@celiacheff We have preexisting "gendarmerie" duplicates, and we could check and remove them at scheduled import time. This patch is a basic PoC.

Deduplicate preexisting and imported gendarmeries.

---

compte/management/commands/purge_inactive_accounts.py
compte/management/commands/purge_tokens.py
core/mattermost.py
erp/admin.py
erp/export/export.py
erp/management/commands/export_to_datagouv.py
erp/management/commands/generate_schema.py
erp/management/commands/import_dataset.py
erp/management/commands/start_scheduler.py
subscription/management/commands/notify_changed_erps.py
tests/compte/test_commands.py
tests/core/test_mattermost.py
tests/erp/export/test_export_integration.py

[Trello card](https://trello.com/c/qhH1iay4/676-envoyer-des-notifications-mattermost-pour-toutes-les-t%C3%A2ches-automatiques)

Post to Mattermost all scheduled command reports.

---

package-lock.json
package.json

Update sentry libraries.

---

api/serializers.py
api/views.py
erp/urls.py
erp/views.py
tests/erp/test_browser.py

[Trello](https://trello.com/c/SyM8HnQz/683-mettre-en-place-une-url-pour-nos-fiches-facilement-reconstituable-%C3%A0-partir-de-luid)

Add a route to resolve erp page from their uuid.

---

.circleci/config.yml
Pipfile
Pipfile.lock

Trying https://github.com/ryanwilsonperkin/pytest-circleci-parallelized

Parallelize python tests in circleci.

---

erp/migrations/0129_commune_contour.py
erp/migrations/0130_auto_20210628_1140.py
erp/migrations/0131_auto_20210628_1554.py

[Trello](https://trello.com/c/IzJHLjpC/684-export-ajout-des-champs-site-internet-t%C3%A9l%C3%A9phone-courriel-lien-vers-outil-de-contact)

autoformat

---

Pipfile
Pipfile.lock

https://www.djangoproject.com/weblog/2021/jul/01/security-releases/

Upgrade Django to 3.2.5.

---

erp/schema.py
templates/erp/includes/accessibilite.html
templates/erp/includes/vaccination.html

[Trello 1](https://trello.com/c/3nQtzRJi/697-ordre-des-informations-sur-laccueil)
[Trello 2](https://trello.com/c/Ct4vVuMU/696-passer-en-gras-les-titres-dans-la-fiche-erp)

Ordre des champs + titres en gras

---

annuaire/views.py
templates/annuaire/index.html

[Trello](https://trello.com/c/zY1POr9K/695-afficher-le-nb-derp-dun-d%C3%A9partement)

Add erp count in annuaire

---

erp/provider/acceslibre.py
tests/erp/test_contrib.py

:warning: double check to be ISO functional with previous version
On a global search made on "restaurant" "Paris", it tooked ~45s, now taking  ~3 s

Fix global search when we have large results.

---

erp/forms.py

Add accent in label.

---

templates/contrib/7-commentaire.html
templates/contrib/includes/nav.html

@z3ntUx I did not touch the section, I think it is better like this, WDYT

Rename comment block.

---

erp/management/commands/create_user.py
erp/management/commands/database_audit.py

Don't know if we have to merge this management command, more here for discussion

Database audit based on import serializer

---

api/views.py

:warning: targetting production

Bring back this distinct.

---

erp/managers.py
erp/views.py

Improve ERP details page, and some managers.

---

erp/models.py
erp/views.py
tests/erp/test_func.py

Be able to display ERP in dom-tom and in cities subdivisions.

---

.env.sample
.isort.cfg
Pipfile
Pipfile.lock
core/settings.py
core/settings_dev.py
core/settings_prod.py
core/settings_recette.py
docker-compose.yml

Tested on staging with a manual deploy on this branch.
Works like a charm.

Setup redis as cache BE.

---

erp/models.py
tests/erp/test_models.py

Be able to compare 2 accessibilities

---

core/mailer.py
tests/compte/test_change_username.py

+ sync all inactive user on deploy

Send activation_key to SIB

---

.circleci/config.yml
Pipfile
Pipfile.lock
erp/provider/generic_geoloc.py
erp/provider/geocoder.py
erp/provider/osm.py

Need to follow support by Scalingo :
https://doc.scalingo.com/languages/python/start#supported-versions

Upgrade python to 3.11(.2)

---

static/js/index.js
templates/stats/index.html

Not sure to follow any best practices here. But it seems consistent with the rest :-D

Change Chart.js init, due to last upgrade.

---

package-lock.json
package.json
static/js/index.js

Cannot find any trace of a previous integration.

Bring back Crisp.

---

erp/forms.py
erp/models.py
erp/views.py
templates/erp/includes/vote-form.html
tests/erp/test_browser.py
tests/erp/test_models.py
tests/erp/test_votes.py

User unvote

---

static/js/geo.js

Fix satellite view, recreate style, change token.

---

api/serializers.py
tests/api/tests.py

Asked by some API users, to be able to know if on a given ERP the latest updated version is on their side or on our side.

Add dates in ERP API

---

erp/provider/entreprise.py
tests/erp/provider/test_entreprise.py

Entreprise Sirene V1 deprecated, move to recherche-entreprises.api.gouv.fr

---

erp/views.py

Use commune (as str) instead of potentially null commune_ext.

---

templates/search/results.html

Remove pagination buttons and page numbers when we use the dynamic map as we are not using pages in this case.

Remove page numbers and pagination on dynamic map

---

package-lock.json
package.json
static/js/index.js

Nothing else to change I guess, can you please confirm @Anto59290

Remove whatwg-fetch.

---

.circleci/config.yml
.github/dependabot.yml
.github/workflows/codeql-analysis.yml
.pre-commit-config.yaml
.prettierignore
.prettierrc.json
cron.json
docker-compose.yml
erp/export/static/base-schema.json
erp/export/static/schema.json
package-lock.json
package.json
static/js/api.js
static/js/dom.js
static/js/geo.js
static/js/index.js
static/js/mapUtils.js
static/js/ui/AsteriskField.js
static/js/ui/ConditionalForm.js
static/js/ui/GeoLink.js
static/js/ui/GetGeolocBtn.js
static/js/ui/LocalisationMap.js
static/js/ui/MapExpander.js
static/js/ui/SearchWhere.js
static/js/ui/index.js
static/js/widget.js
static/parcel-entry.js
static/scss/style-dsfr.scss
static/scss/style.scss
static/scss/styles.js

Basic prettier config to discuss @Anto59290

Add prettier

---

static/js/ui/SearchWhere.js

Remove duplicated code (autocomplete.input.addEvtList) 
Enable search button when entry is selected via Enter key

Activate search button on selection via Enter

---

erp/views.py
templates/contrib/1-admin-infos.html

- Remove unused computed geoJSON (added in https://github.com/MTES-MCT/acceslibre/commit/1050ed82422f75039fe5f4f7202ecb27e5093c95 but the map has been removed in
https://github.com/MTES-MCT/acceslibre/commit/dbb7b45068a329cc09d14c573df249c9f52da4b9)
- Get only activity id

Remove unused computation in contrib admin info.

---

templates/registration/login.html

Use a span for login buttons, all on same line.

---

api/permissions.py
tests/api/test_permissions.py

Fixes https://sentry.incubateur.net/organizations/betagouv/issues/54079/?alert_rule_id=16&alert_timestamp=1689149886923&alert_type=email&environment=production&project=35&referrer=alert_email

Manage bad format for api-key

---

locale/en/LC_MESSAGES/django.po
locale/fr/LC_MESSAGES/django.po
templates/erp/includes/header.html

On ERP detail view only, but kept on search map.

Remove locate on map

---

templates/index.html

Template cache per language

---

erp/provider/entreprise.py
erp/provider/opendatasoft.py

- [ODS] remove unreachable code (except timeout)
- [ODS] log error if dataset is unknown, so that it will not be a silent error anymore
- [ODS] change dataset name
- [recherche-entreprise] use business name, more relevant.

Enhance external search APIs.

---

compte/signals.py
core/mailer.py
tests/compte/test_change_username.py

TODO on deploy : sync all users

Sync NB_ERPS to Brevo for mail campaign.

---

static/js/api.js

Compute length on trimmed str sent to the API.

---

stats/admin.py

BTW searching into urlpath seems enough.

Cannot search on a foreign key.

---

static/scss/style.scss

So that autocomplete result list go upper label tags.

Adjust z-index

---

static/js/geo.js
static/scss/loader.scss
static/scss/style.scss
templates/search/results.html

This commit will add a spinner (loader) while waiting for the response of the API ERP. This allows the user to know that the action he made has worked and that we are processing the request (visual feedback, retroaction).

Add a spinner when calling API on ERP map

---

erp/views.py
static/scss/style.scss
templates/contrib/0-start.html
templates/contrib/base.html
templates/django_registration/registration_complete.html
templates/django_registration/registration_form.html
templates/editorial/base.html
templates/erp/index.html
templates/registration/login.html
templates/search/form.html
templates/stats/index.html

Manage left&right spacing.

---

static/scss/style.scss
templates/contrib/forms/search.html
templates/search/form.html

Add text on search button in both search & contrib.

---

locale/en/LC_MESSAGES/django.po
locale/fr/LC_MESSAGES/django.po
static/scss/style.scss
templates/contrib/forms/search.html
templates/search/form.html

With new search button with text, it requires some adjustements:

Adjust contrib start layout.

---

erp/provider/search.py
erp/views.py
static/scss/style.scss

Always relay activity slug and pk to the contrib admin page to prepopulate the drop down.
Also adjust bouton hover color.

Send activity to contrib admin infos page.

---

static/js/widget.js
templates/erp/widget/base.html

Make some adjustments to controlled widget

---

core/lib/text.py
erp/managers.py
tests/core/test_text.py

Remove dead code from managers and core.lib.text.

Remove dead code

---

erp/views.py

- It looks like the step argument can never be 8 or 9, allowing us to make the function simpler
- Remove useless redirect_hash

Simplify process_accessibilite_form function

---

static/js/api.js
static/js/ui/GetGeolocBtn.js
static/js/ui/SearchWhere.js

- Increase the timeout: on FF it was reaching the timeout before being able to retrieve the coords. It is much more slower on FF than on Chrome
- Reduce code complexity, was here only to be able to display a label

browser geoloc

---

templates/erp/includes/vote-form.html

One of the last places where we use jquery

Rewrite existing script without jQuery

---

static/js/ui/SearchWhere.js

If we use geoloc acquisition, we do not have code, we only get lat & lon

Activate button if geoloc position acquired.

---

locale/en/LC_MESSAGES/django.po
locale/fr/LC_MESSAGES/django.po
static/scss/style-dsfr.scss
static/scss/style.scss
templates/contrib/includes/nav.html

On the contribution pages rewrite the navigation / steps component, the initial goal was to remove the use of jQuery.
- Merge mobile and desktop code
- Use component from DSFR instead of our own
- Remove some CSS

Rewrite navigation component for contribution

---

erp/views.py

Reproduce the logic made on contrib_admin_infos. Maybe not the perfect fix, and maybe things to factorize here and there.

Save activity on edit mode.

---

erp/managers.py
erp/provider/search.py
locale/en/LC_MESSAGES/django.po
locale/fr/LC_MESSAGES/django.po
static/js/ui/GroupLabelTag.js

New spec : if all equipments of a shortcut are unchecked, do not uncheck the shorcut anymore, and let the suggestions as they were.
Change some wording / suggestions and equipments.

Adjustments on filters.

---

erp/imports/mapper/service_public.py
erp/imports/serializers.py
erp/management/commands/convert_tally_to_schema.py
erp/management/commands/validate_and_import_file.py
tests/erp/imports/mapper/test_service_public.py

- Change activity mapping
- Use the import serializer

SP import, use serializer, fix activity mapping

---

static/js/widget.js

The missing header was making the tracking out of service.

Fix issue with widget tracking

---

erp/management/commands/outscraper_clean_closed.py

Sometimes we have no business status

Avoid KeyError

---

erp/imports/mapper/service_public.py
erp/management/commands/outscraper_acquisition.py

- create a revision when saving with outscraper acquirer
- avoid matching on empty values in SP, catch reversion error

Adjust SP importer, create revision in import

---

erp/duplicates.py
erp/models.py
tests/erp/test_duplicates.py

A ERP that has been attributed to a user is now viewed as a trustable source of information.

Add new rule for duplicate detection

---

api/filters.py
api/views.py
tests/api/tests.py

Allow to filter on date created / updated for ERPs and Accessibilite using an API filter.

Allow to filter on date on API

---

erp/management/commands/scrapfly_acquisition.py

- Add entree_porte_presence by default
- remove unused args
- make checkin/out dates dynamic
- manage case where there is no result

Scrapfly adjustments

---

locale/en/LC_MESSAGES/django.po
locale/fr/LC_MESSAGES/django.po
static/scss/style.scss
templates/contrib/base.html

Was introduced in 8a6a420ed682e2fb0f30284ddeed560864b2403d but the trigger has been removed.

Remove useless spinner HTML and CSS

---

erp/fields.py
static/js/ui/AutocompleteActivity.js

"Hot" should return "Hôtel"
"Muse" should return "Musée"

Make autocomplete case and accents insensitive

---

static/scss/style.scss

Remove useless CSS

---

api/filters.py

The bug it is solving: looping trough all api list pages was not returning all ERPs.
We can not use `queryset.ordered` here, as queryset is always ordered (Meta ordering in model).
:warning: targetting production

Always order by pk

---

erp/imports/serializers.py
tests/erp/imports/test_import_laposte.py
tests/erp/imports/test_serializers.py

New definition of duplicates in import: now also searching by exact name in the 75m around.

Consider same name in 75m around as a duplicate in import.

---

locale/en/LC_MESSAGES/django.po
locale/fr/LC_MESSAGES/django.po
static/scss/contribution.scss
static/scss/half-circle-progress-bar.scss
templates/contrib/contribution-base-success.html

- Reduce the size of the progress bar
- Change titles / font-weights
- Change button spacings

Minor design changes on contrib success page

---

erp/models.py
subscription/management/commands/notify_changed_erps.py
tests/subscription/test_commands.py

Intented to be read commit per commit, details in commit messages.
This PR has been initiated from production branch

Fix ERP notifications changed.

---

erp/management/commands/import_laposte.py

entree_plain_pied is False if ACH0015 False.

---

erp/forms.py
tests/subscription/test_commands.py

If the adresse_changed we were forgetting the manual relocation (cleaned_data lat & long) as self.geocode was replacing lat & long

Fix the manual ERP relocation.

---

erp/management/commands/start_scheduler.py

Should be probably reset to 30 days after DDT challenge.

Keep 70 days of revisions.

---

.gitignore

My usage: have a command named `local_post_pg_restore` which create some fixtures / assign some ERP to a given users once I have restored a dump from prod env.

Be able to have some local management command.

---

erp/models.py
erp/schema.py
erp/templatetags/a4a.py
erp/views.py
locale/en/LC_MESSAGES/django.po
locale/fr/LC_MESSAGES/django.po
static/scss/style.scss
templates/erp/includes/access_accommodation.html
templates/erp/includes/access_entrance.html
templates/erp/includes/access_legal.html
templates/erp/includes/access_outside_path.html
templates/erp/includes/access_parking.html
templates/erp/includes/access_reception.html
templates/erp/includes/access_stairs.html
templates/erp/includes/access_steps.html
templates/erp/includes/access_value.html
templates/erp/index.html

This commit adds 2cff9f71b6c9577589d07effe907478d76dbae11 and 092e292bfce43b8b06e563b8f760aa6190fd17de back to the branch. Also add new texts in the schema and use them in template tags.

Introduce new display of access data on ERP detail

---

erp/management/commands/start_scheduler.py
stats/queries.py

- adjust cron to match the schedule we've communicated in t&c
- initial version contains fields with `'[]'` as value

Post QA fixes

---

erp/models.py
erp/schema.py
locale/en/LC_MESSAGES/django.po
locale/fr/LC_MESSAGES/django.po
templates/erp/includes/access_accommodation.html
templates/erp/includes/access_entrance.html
templates/erp/includes/access_outside_path.html
templates/erp/includes/access_parking.html
templates/erp/includes/access_reception.html
templates/erp/includes/access_steps.html

Most of the commit is fixes of positive / negative / unknown cases. Rewrite a few sentences.

Improve data display on ERP detail page

---

templates/erp/includes/access_comment.html
templates/erp/index.html

- Add the free text comment field on the ERP page (new version)
- Fix typo to display legal informations

Display legal info and comment on ERP page

---

erp/management/commands/fix_inconsistency_root_child_questions.py
erp/management/commands/outscraper_acquisition.py
erp/schema.py
static/js/ui/ConditionalForm.js
static/scss/style.scss

This PR is intented to be read commit per commit

Various fixes around root/non root questions + script for audit.

---

erp/models.py
static/scss/style.scss
templates/erp/index.html

- Add new logic to take the most recent date between 3 dates
- Review the design of the display

Add new rule for "updated at" date on ERP page

---

api/serializers.py
erp/export/utils.py
erp/views.py
erp/widget_utils.py
tests/api/tests.py

Do not concatenate list elements anymore. Let the client managing how to display this list.

Render list access info as list in widget API.

---

tests/erp/imports/test_import_laposte.py

Make sure the factories are called with the proper parameters. This will ensure us the test is valid all the time.

Fix test flakiness on La poste import

---

erp/models.py
erp/schema.py
locale/en/LC_MESSAGES/django.po
locale/fr/LC_MESSAGES/django.po
templates/erp/includes/access_entrance.html
templates/erp/includes/access_outside_path.html
templates/erp/includes/access_parking.html
templates/erp/includes/access_reception.html
templates/erp/includes/access_stairs.html
templates/erp/includes/access_steps.html

Fix a few mistakes here and there on the new ERP detail page.

Add various text fixes to the ERP detail page

---

erp/management/commands/convert_tally_to_schema.py

We cannot answer to a child question if the mother one has not been answered.

Fix mapping for tally conversion.

---

erp/forms.py

Regression introduced by :
https://github.com/MTES-MCT/acceslibre/commit/9cccaf34465a2771d5960a2214ba9412e9f524dd

While contributing, search only in published ERPs

---

core/sitemaps.py
erp/views.py
tests/core/test_sitemaps.py
tests/erp/test_search.py

We cannot use select_related here, resulting into database performance issue.

Remove select_related. (#1383)

---

erp/views.py
tests/erp/test_search.py

Fix a case where the page for the municipalities with the same name (for example "Saint-Pierre" which exists in 974, 15, 31 and many more). In this case:
- All the ERPs from the cities called Saint-Pierre where listed
- The map was centered in the middle of Africa
Fix the issue by filtering also on the departement, we are OK this may not work if we have to cities with the same name in the same departement.

Fix municipality view for municipality with same name

---

erp/forms.py
tests/erp/test_browser.py

Make sure the postal code is passed when trying to create a new ERP.

Fix postal code not being passed in contrib search

---

templates/erp/includes/access_entrance.html

Fix negative case on the ERP details page.

Fix display of entree_vitree_vitrophanie on ERP

---

templates/erp/includes/access_reception.html

Improve the display of hearing equipements on ERP details page.

Improve display of hearing equipements on ERP

---

locale/en/LC_MESSAGES/django.po
locale/fr/LC_MESSAGES/django.po
templates/erp/includes/access_reception.html
templates/erp/includes/access_value.html
templates/erp/includes/filters.html

- Fix a typo that was causing some bullet points to be shown for every filters
- Add title
- Add filter for wheelchair

Fix missing filters on ERP detail page

---

erp/management/commands/convert_tally_to_schema.py

Source has been manually changed in converted file. Might be interesting in future to make the source dynamic or tally dependant.

Manage ATH in tally conversion

---

templates/erp/includes/access_accommodation.html

When unsure we decide not to show any information instead of a negative text.

Improve text for hotel room when no data

---

Pipfile
Pipfile.lock
pytest.ini
tests/html/test_html.py

We will have to decide what to do with those tests using external HTML validator

Disallow network calls in tests.

---

compte/signals.py
tests/erp/test_browser.py

To be dropped once initial superuser are set up.

Use a waffle switch for 2FA

---

erp/management/commands/convert_tally_to_schema.py

Keep the old answer for back compatibility

Additional possible answer for parking question.

---

api/filters.py
tests/api/tests.py

with_drafts is a string, which can be "true" or "false".

Fix with_drafts

---

locale/en/LC_MESSAGES/django.po
locale/fr/LC_MESSAGES/django.po
templates/erp/includes/sidebar.html
templates/erp/includes/versions_block.html
templates/erp/includes/widget_block.html

- Fix a few typo / texts here and there
- Change the headings size

Fixes design and texts on ERP details page

---

erp/management/commands/delete_users_erps.py
tests/erp/test_command_delete_users_erps.py

Add a command to delete ERPs created by a specific user with a few rules.

Add command to delete ERPs from user

---

erp/management/commands/convert_tally_to_schema.py

As we are now using those Tally questions for non labelized ERPs, we cannot assume they are all labelized TH.

Do not put labels=TH for all ERPs

---

erp/managers.py
tests/erp/test_managers.py

- if we have a numero, we have to search for this exact number or None
- if we have no numero, we search for this activity on all street

Find duplicate, numero None matches

---

erp/export/static/schema.json
erp/models.py
erp/schema.py
locale/en/LC_MESSAGES/django.po
locale/fr/LC_MESSAGES/django.po
templates/erp/includes/access_reception.html

Make the texts a little bit more detailled, change a question in the contribution flow.

Change texts on ERP pages

---

static/js/geo.js

Make sure we don't focus on the ERP but on the municipality.

Fix zoom on the contour of the municipality

---

erp/management/commands/export_to_datagouv.py

Time divided by 2 on a sample (10,000k ERP)

Use select_related in export_datagouv

---

api/filters.py

Fix typo preventing from sorting by department code

---

.circleci/config.yml

Already using pg15 on staging + prod env.

Move to postgres15

---

erp/views.py

Quick fix, might be a good idea to have a global approach for such cases

Fix for Corse postal code.

---

erp/management/commands/cancel_user_modifications.py
tests/erp/test_cancel_user_modifications.py

username__icontains is not enough to identify a user, better to use email which is unique.

Search user by email.

---

stats/models.py
stats/signals.py
stats/tasks.py
tests/stats/test_models.py

Since a user can change his username... (I think I don't have to finish my sentence :) )

Index challenge score by user_id instead of username

---

static/js/mapUtils.js
static/scss/style.scss
templates/challenge/detail_v1.html
templates/challenge/detail_v2.html
templates/common/challenge_item.html
templates/contrib/includes/prevnext.html
templates/editorial/header.html
templates/editorial/partenaires.html
templates/editorial/qui-sommes-nous.html
templates/index.html

- Added missing icon "house" for "Accueil" in the navbar
- Replaced icon for connexion button in the header
- Checkboxes in the contribution form weren't aligned anymore due to the DSFR package upgrade. Removed the class responsible for this (Custom class, not DSFR related)
- Fixed various places where links were not in right format (Mostly on the homepage and in the partners page)
- Challenges page -> Remove double underlines
- In the Cartographie page, remove the image being underlined, only the link should be underlined
- Replace some of the Bootstrap btn classes to use DSFR ones
- https://trello.com/c/wEo9rcri/2095-header

[Frontend] Header missing icons + various other fixes (Links + spacings) 

---

templates/base.html

When switching languages, some translations used to not be translated correctly.
Added query parameter ?lang when injecting the django-js script for the translations to sync properly when switching languages

[Frontend] Attempt to fix - Updated javascript-catalog script injection

---

erp/management/base_acquisition.py
erp/management/commands/outscraper_acquisition.py
erp/management/commands/scrapfly_acquisition.py
tests/erp/test_commands.py

- use base class for acquisition management commands
- move common code
- do not create revision if not changes made
- manage potential error on geocode

Scrapfly acquisition revisions management

---

static/index.js
static/js/ui/SyncInputsWithElement.js
static/js/ui/index.js
templates/contrib/1-admin-infos.html

- Component to sync input values with another HTML element
- sync input address with span#erp-address

Sync ERP address

---

erp/views.py

initial is overriding values from instance, this is not what we want here. We want a default value in case of missing info on instance, but we want the instance value if defined.

Fix initial value when having an instance.

---

static/js/ui/ContribPagination.js

Bugfixes for :
- Pagination, don't display the View more button correctly.
- Use of parameter "code_insee" instead of "around" when calling the API to retrieve ERPs

[Frontend] Parcours de contribution

---

templates/erp/includes/ctas.html
templates/erp/includes/filters.html

[Frontend] ERP Details feedback part 2

---

static/scss/_erp-details.scss
templates/erp/includes/header.html

Text was overflowing in the address section

[Frontend] ERP Details page - Text ellipsis bugfix

---

static/js/ui/FormContribDirtyChecker.js

[Frontend] Contrib - Redirection security fix

---

static/scss/_utilities.scss
templates/erp/includes/header.html

- Removed ellipses and added word-break instead

[Frontend] ERP Details page - Removed ellipsis and added word-break

---

compte/forms.py
locale/en/LC_MESSAGES/django.po
locale/fr/LC_MESSAGES/django.po
templates/django_registration/registration_form.html

⬆️ 
https://trello.com/c/ge3KTaPI/2221-page-creation-de-compte-rajouter-checkboxes-afficher-dans-les-champs-mots-de-passe

[Frontend] Registration form - Added checkboxes to display both passwords

---

templates/editorial/qui-sommes-nous.html

- Nous rejoindre button link updated

[Frontend] Qui sommes nous page, link update

---

templates/editorial/qui-sommes-nous.html

[Frontend] Qui sommes nous - img path fixes

---

templates/compte/includes/mes_challenges_list.html

[Frontend] Mon compte - Mes challenges, added margin to button

---

templates/compte/base.html

- Default landing to ongoing challenges

[Frontend] Feedback - mes challenges

---

core/settings.py
static/scss/_faq.scss

[Frontend] FAQ Article - Font family explicily set for FAQ Articles + reduce available options in summernote editor

---

static/scss/_faq.scss

[Frontend] font-family force on faq articles increase specificity

---

static/js/geo.js
static/scss/_main-search.scss
templates/search/results.html

⬆️ 
https://trello.com/c/5p8h8Tob/2344-vue-communes-p%C3%A9t%C3%A9e

[Frontend] Commune search fix

---

.dockerignore
Dockerfile
docker-compose.yml

- Dockerised the django application & updated docker-compose
The data still needs to be injected through the container's command line.
Example :
```sh
> docker compose exec -it <container_id|container_name> sh
> pg_restore --clean --if-exists --no-owner --no-privileges --dbname "postgres://access4all:access4all@localhost/access4all" your_dump.pgsql
```
The dump file needs to be located in the host volume folder data_psql (at the root), check the mounted volume in the docker compose file : 
```yml
volumes:
- ./data_psql:/data_psql
```
- https://trello.com/c/7Bo3fvAB/2372-dockerise-the-django-application

[Backend] Dockerised application

---

package-lock.json
package.json

The upgraded version  should fix the bugs that have been introduced in the previous version according to Adrien Pavie
- https://trello.com/c/ORk4Gqxr/2366-outil-panoramax-bug-qd-on-clique-sur-les-vues-dans-le-plan

[Frontend] Upgraded package panoramax

---

templates/challenge/detail_v1.html
templates/challenge/detail_v2.html
templates/common/challenge_item.html

- Text no longer centered
- Use of Highlight for "accroche" text
- Use of truncatewords for ongoing challenge text
- https://trello.com/c/iGCxcSj9/2373-pages-challenges-challenge

[Frontend] Challenge pages ui fixes

---

templates/challenge/detail_v1.html
templates/challenge/detail_v2.html
templates/common/challenge_item.html

- Challenges page => In challenge cards, use "accroche" instead of "text_reserve"
- Challenge page => Move "Sign up button" between "accroche" and "text_reserve"

[Frontend] Challenge pages more tweaks

---

templates/erp/includes/header.html

⬆️ 
- https://trello.com/c/jZNN5Ute/2378-pb-lien-sites-externes

[Frontend] chore: external link bugfix on erp details

---

.talismanrc
compte/forms.py

Fix forget password email

---

.talismanrc
templates/registration/password_reset_confirm.html

[Frontend] chore: password reset form page, fields classes and error added
