Pipfile
Pipfile.lock
erp/models.py

Release notes: 
- https://www.djangoproject.com/weblog/2020/aug/04/django-31-released/
- https://www.djangoproject.com/weblog/2020/sep/01/security-releases/

Upgrade Django to 3.1.1.

---

erp/forms.py
tests/erp/test_forms.py

[Trello card](https://trello.com/c/MMDa79PN/290-emp%C3%AAcher-linscription-avec-un-nom-dutilisateur-username-au-format-adresse-email)

Restrict username format in public user registration form.

---

erp/forms.py
erp/geocoder.py
tests/erp/test_forms.py

> Bonjour,
> J'ai trouvé l'établissement que je veux renseigner (siret 82250607700012).  Mais l'adresse rapatriée (5 Avenue DU PONT NEUF 74960 ANNECY) n'est pas reconnue.
Dans ce cas précis, il s'avère que l'API Sirene de L'INSEE nous expose l'adresse suivante pour l'établissement concerné : `5 Avenue DU PONT NEUF 74960 ANNECY`, mais le problème c'est que `74960` n'est pas le code postal d'Annecy, mais celui de Cran-Gevrier (ville juste à côté).
Ce faisant, la requête envoyée vers la BAN pour géolocaliser l'adresse renvoie un résultat peu pertinent du fait de ce code  erroné.
Partant du constat que les données issues du registre Sirene ne sont pas forcément fiables ou actualisées au niveau du code postal, ce patch tronque ce dernier pour n'en retenir que les deux premiers caractères, …

Better handle bad postcodes.

---

templates/contrib/base.html

[Trello card](https://trello.com/c/n9FKBgD0/330-nafficher-que-l%C3%A9tape-en-cours-en-vue-mobile)

Expose a compact step selector for handset viewports.

---

erp/versioning.py

Sentry issue : https://sentry.data.gouv.fr/access4all/access4all-django/issues/1893350/
> `error'NoneType' object has no attribute 'is_online'`
> erp/versioning.py in extract_online_erp at line 23
This might occur when a versioned object has been deleted.

Fix error when a versioned object is empty.

---

erp/views.py
templates/contrib/1-admin-infos.html
templates/contrib/2-localisation.html
templates/contrib/base_access_form.html
templates/contrib/includes/prevnext.html
tests/erp/test_browser.py

We don't have a Trello link but this is a blocking bug: contributors on an Erp don't have convenient navigation links for accessing previous and next steps in the contribution workflow. This patch attempts at "cleaning" existing links, make them responsive and ensure *previous* and *next* links are rendered every time they need to.

Revamp contrib workflow navigation links.

---

core/lib/text.py
erp/mapper/vaccination.py
tests/core/test_text.py
tests/erp/mapper/test_vaccination.py

We keep importing vaccination centers reserved to professionals and "équipes mobiles", while we shouldn't. 
To prevent these imports, this patch: 
- adds a few more rules and checks for professionals and équipes mobiles;
- checks presence of these rules in both `nom` and `modalites` fields.

Update vaccination record mapper checks.

---

erp/mapper/vaccination.py
tests/erp/mapper/test_vaccination.py

[Trello](https://trello.com/c/0RjV5z3P/561-ne-pas-%C3%A9craser-les-commentaires-saisis-par-les-gestionnaires-de-centres-de-vaccination)

Avoid overriding contributor comments when importing VC updates.

---

erp/managers.py
erp/provider/departements.py
erp/templatetags/a4a.py
erp/views.py
static/js/dom.js
static/js/ui/SearchWhere.js
templates/search/form.html
templates/search/results.html
tests/erp/export/test_export_unit.py
tests/erp/test_browser.py
tests/erp/test_managers.py

This patch improves the relevance of search queries by searching for results around the center of the city and ordering by ascending distances, so we can retrieve results in neighboring cities, which makes a better UX when there are very few (or no) results for a given city.

Improve commune centered search

---

erp/forms.py
erp/templatetags/a4a.py
templates/contrib/base_access_form.html

@z3ntUx This is only a suggestion, I did the same we are doing for `schema`. You might have a better idea.

Get a label for form field, used in form.errors.

---

erp/views.py

:warning: Targeting `production`
Reported by Sentry

Avoid 500 error if empty "what" in global search.

---

templates/base.html

Previously, we used matomo tag manager to integrate Crisp. Crisp is now integrated in our codebase, we don't need this tag manager anymore.

No more tag manager.

---

erp/provider/arrondissements.py
erp/views.py
tests/erp/test_search.py

`kwargs['municipality']` can contains district details like "Paris 6e Arrondissement", this PR suggests to only use postcode to filter ERPs.
There are many other solution, like cleaning the district details from the municipality name. Or any other work on municipality string. Let's discuss it.
Edit: need to manage cities with same postal code.
Edit2: now cleaning the municipality string to remove district details. Double `re` usage to challenge. Consider this PR as a suggestion, a base for a discussion :-D

Search by municipality, manage districts

---

static/js/geo.js
static/js/mapUtils.js

Handle a Js error that could happen when an ERP has no activity linked (it looks like this should never happen but that's another issue).
- Default to building icon if no activity (was already the default behavior)
- Lint the file
https://sentry.incubateur.net/organizations/betagouv/issues/48172/ FIX ACCESLIBRE-154

Handle case where an ERP has no activity on map

---

erp/views.py

cheminement_ext_terrain_stable should be strictly False, if unknown it should not display "Accès difficile"
:warning: target production

Change condition to display "Accès difficile"

---

templates/common/map.html

The typo was causing the ERP not to be highlighted / showcased. This was introduced in 1e8cd7b207cce373917d019262c9e8f15e3c931d

Fix showcase of specific ERP on ERP details page

---

core/sitemaps.py
tests/core/test_sitemaps.py

When looking at Sentry we can see that the sitemap for the ERPs is having an issue: mean loading time of 1.58s and p95 of 2.16s. When looking at this data you have to take into account that this view is using a cache, that means that some hits are served in ~5ms (which has a lot of impact on mean and p95).
Looking at the trace you can see that the main issue is the page making a lot of SQL queries (around 1000 per page if my understanding is correct - the real number can't be seen in Sentry for whatever reason).
The issue is that we need to get the `activite` of the `ERP` (or at least the slug) to create the URL of the ERP that is used in the sitemap.
The issue is fixed using a select_related, this could be improve if needed by loading only the fields that are needed using `.only()`.
Add …

Improve performances of the sitemaps for ERPs

---

package-lock.json
package.json

This is not used directly into our code and is already bundle with Boostrap. It is also outdated.
It was introduced in e06f72999cd4c944121fb3afc6e158c2dbd6b10e were Bootstrap was also added in the `index.js` file, leading me to think the first attempt was using Popper but that Bootstrap was chosen instead (Bootstrap was already installed).

Remove Popper.js

---

static/js/geo.js

We had an issue when merging 2 PRs: one displaying the map when no results, the other one allowing for infinite scroll.

Fix map display when no results

---

erp/provider/entreprise.py
tests/erp/provider/test_entreprise.py

We were naively returning coords from API result, whereas it does not follow the format we except.
It was resulting into locating ERP somewhere in Africa.

Fix ERP mislocated when using enterprise API

---

static/js/index.js
templates/editorial/header.html

In the future we are going to start using the Js part of the French Design System (for tabs, tags, etc).
To do so we need to add the Javascript file to the index.js file. When doing so the DSFR will generate a JS error because our HTML markup for the header is not valid (at least not from the DSFR point of view).
This commit fixes the markup so that we don't have this error for now. This does not mean we have a fully fonctionnal menu / header from the DSFR point of view as this would mean more work and some changes in the behavior / UX of the menu.
The DSFR *needs* this specific markup to be there for the component to work.
https://github.com/GouvernementFR/dsfr/blob/main/src/component/header/script/header/header-links.js#L12

Add Javascript file for DSFR and fix markup

---

api/permissions.py
core/settings.py

This commit optmize the time spent to verify an API key.
Using two classes in `DEFAULT_PERMISSION_CLASSES` was causing an increase in latency for all API views. This is due to the fact that both the `HasAPIKey` and `IsAllowedForAction` classes are checking for the existence of the key using `get_from_key` (this calls a `is_valid` method which is doing some criptographic verifications that are slow).
As the `IsAllowedForAction` class is already checking the key, we don't really need the `HasAPIKey` class.
This commit also add a custom span so that in the future we know what is happening in the traces (avoiding a big blank in sentry)

Optimize API Key verification

---

erp/views.py

Fix an issue that would happen when a user would go on a municipality page and then add a "what" term to the search without adding any new parameter.

Fix issue when adding "what" to search on city page

---

core/sitemaps.py

Explicitely tell how to get the latest element's update date.
Before this change, it was taking more than 30s to generate the sitemap.xml
After it takes ~ 500ms on localhost, without any cache.
Without this change, it was based on `def lastmod` and looping through all
elements to perform a `max()`. See the following block code coming from Django
sitemap:
```py
def get_latest_lastmod(self):
if not hasattr(self, "lastmod"):
return None
if callable(self.lastmod):
try:
return max([self.lastmod(item) for item in self.items()],
default=None)
except TypeError:
return None
else:
return self.lastmod
```
I am not sure we should perform so heavy SQL requests for this need, but at
least it works as before.

Enhance sitemap perfs.

---

erp/urls.py
erp/views.py
stats/queries.py
stats/views.py
templates/index.html

Due to the cache that was added on the homepage route, the CSRF token for the language selection was outdated most of the time, leading to a CSRF error.
- Fix the CSRF error by removing the cache on the route
- Add cache on the only part of the template that was a bit long (displaying statistics, which needs some expensive DB queries)
- Rewrite the queries so that they can be kept lazy until the template block - it seems the .count() operation is never kept lazy when passed into the context. I passed queryset instead and moved the count operation in the template.

Fix CSRF issue on homepage and remove cache

---

core/sitemaps.py

The longest part is the template rendering, 10000 objects was too much ! Use `only('slug')`, as the only thing we need is things in `def get_absolute_url`.

Reduce nb communes displayed per page.

---

static/js/widget.js

Fix JavaSciprt error that could occur when Matomo is blocked (example: with Ublock Origin). This would led to some errors further down, just mock the only function we use in this case.
Fix ACCESLIBRE-19N
Fix ACCESLIBRE-19M
Fix ACCESLIBRE-19P
Fix ACCESLIBRE-19Q

Fix JavaScript error when trackers are blocked

---

static/js/index.js
static/js/ui/SearchWhere.js
templates/contrib/forms/search.html
templates/search/form.html

Let the `activateSubmitBtn` function responsible for checking if the button should be enabled or not.
If provided address is not valid, `code` will remain empty and so, we should not force the button to be enabled.
Remove spinner. Seems useless, if it need to be bring back, it should be done in a better manner.
Move the `activateSubmitBtn` in onSubmit, so that if search data is emptied it will not activate the button.
The 2 scenarios to test :
- an invalid address should not activate the button
- choosing an entry with the keyboard (enter key) should activate the button

Do not force submit button to be enabled.

---

Pipfile
Pipfile.lock
conftest.py
core/sitemaps.py
erp/export/export.py
erp/forms.py
erp/provider/public_erp.py
erp/views.py
templates/contrib/1-admin-infos.html
tests/erp/test_contrib.py
tests/erp/test_schema.py
tests/factories.py

This commit will avoid the creation of a new revision on the ERP object, when it's edited without any changes in the first step of the contribution edit flow ("infos" step)
This is the first step to make sure that going thought the edit flow without any change does not trigger the creation of a revision (more work needs to be done in this direction).
- Add django-webtest to make sure it is easier to test forms / contribution flows
- Add more fixture to ease testing
- Make sure we call the .save() method only when some changes were actually made:
- Use Decimal for the initial data, this will be used in the Django
internal to determine if the data has changed (`has_changed` method of the field object). As the field use the form is a DecimalField the cleaned data will be using a Decimal …

Avoid creation of revision when no changes on ERP

---

erp/views.py
tests/erp/test_search.py

Pre fill the contrib form with postal code coming from the `where` autocomplete. If the user provides a street name, it was previously put in the city field. Now parsing it, to be able to fill in the city field with only the municipality name.

Pre fill contrib form with postal code, fix street input.

---

static/js/geo.js

In order to be able to retrieve our search when performing a "previous page" action, automaticcaly add filters and shortcuts in request.GET.

Auto add filters and shortcuts in URL.

---

erp/models.py

When decoding provided encoded data (provided by external services or internally by api responses), numero (or other field) can be int, cast it into str to be able to manage both types.
Fixes ACCESLIBRE-1AT

Numero can be int.

---

templates/contact_form/contact_form.html

robot is required in the form, so it can't be hidden for authenticated users otherwise it raises a form.error.
This could be enhance if we really don't want to have authenticated users to check this box. But at least it mitigates the pb.

Contact form was not submittable if authenticated

---

templates/contrib/forms/search.html

On JS side, some code are based on the presence of a div.equipments, acting as a feature flag. Display the div only if we have equipments.

Hide div if no equipments

---

static/scss/style.scss

On small screens (vertical height under 950px but with a "large" / non mobile display) the autocomplete of the "where" field would go under the header, making it impossible to click on the first n elements.
Change z-index of the autocomplete in order to fix this.

Fix autocomplete display on small screens

---

erp/views.py

The dict key to render the template had been renamed into https://github.com/MTES-MCT/acceslibre/commit/8ef316d9eb3c35e3f6f1637d7ab9dac72a7ceef0 but this change had not been reflected in the edit part. Get only the ID, we have no need of other attributes.

Get other_activity in edit mode.

---

stats/middleware.py
tests/stats/tests.py

Fix an issue with widget tracking when the referer URL is > 200 characters.
Fix ACCESLIBRE-1C8

Fix issue with widget tracking when URL is long

---

stats/middleware.py
tests/stats/tests.py

Fix an issue with widget tracking when the referer URL is > 200 characters.
Fix ACCESLIBRE-1C8

Fix issue with widget tracking when URL is long (#865)

---

stats/middleware.py
tests/stats/tests.py

Remove query strings when saving info for widget tracking as it is not a really valuable information.

Remove query strings from widget tracking

---

erp/views.py
tests/erp/test_contrib.py

This field will be b64encode on template side with `encode_provider_data` and then decoded in contrib admin infos views.
This will allow to prepopulate the activity field.

Relay activity to the contrib admin info page

---

static/js/widget.js

getTrackers is now returning an array of trackers. If we want to mock it we have to return a list of fake trackers.

Fix our demo widget with multi tracker.

---

static/js/ui/SearchWhere.js
templates/contrib/forms/search.html

- Ignore shift and control, those keys should not empty the search values, i.e. if you perform a shift tab to go to the activity field, it should not wipe the where autocomplete
- add a required on the what field, so that it acts as the activity field, with a direct message if empty.

Ignore shift and control on autocomplete, add a required on what.

---

api/filters.py
api/views.py
tests/api/tests.py

Allow the users using the API to list un-published (drafts) ERPs using a query parameter / filter. Add test.

Allow API to show un-published ERPs

---

erp/views.py
tests/erp/test_search.py

`geojson_list` disappeared, as direct consequence, the infinite scroll was not working anymore.

Bring back geojson_list for JS.

---

static/js/widget.js
templates/common/matomo.html

The primary tracker on widget side becomes stats.beta, the secondary is matomo.cloud.
On website, we now only use stats.data.

Split matomo widget & website.

---

erp/managers.py
tests/api/tests.py
tests/factories.py

Remove unused Commune.search function.
Use trgm similarity on search to have a higher weight on exact matches. Ex: searching for cultura should first return ERP with name Cultura and then ERP with name containing Culture.

Use trgm_similarity on search.

---

templates/common/matomo.html

Part of the work to globally remove JQuery from the whole codebase

Remove JQuery usages from matomo.

---

erp/exceptions.py
erp/models.py
tests/erp/test_models.py

This will merge only the accessibility data and not the ERP itself. The method is added on the ERP model to ease the use.

Add a merge operator for ERP

---

erp/imports/mapper/gendarmerie.py
erp/imports/mapper/generic.py
erp/imports/mapper/nestenn.py
erp/imports/mapper/vaccination.py
tests/erp/imports/mapper/test_gendarmerie.py

Remove all occurences of `commune_ext =
Commune.objects.filter(code_postaux__contains=[self.erp.code_postal]).first()` This line is not correct and does not work for cities having the same postal code, it takes the first one without checking if it matches the city passed in the record.
Put all logic to retrieve commune_ext into a base function, change all mapper to inherit from the base one.
TODO

Do not set an approximative CommuneExt in imports.

---

erp/forms.py
erp/provider/departements.py
tests/erp/provider/test_departements.py

ATM there is a bug on api-adresse, it does not return postal_code for TOM ex https://api-adresse.data.gouv.fr/search/?q=41+Avenue+FOCH%2C+NOUMEA&limit=1 So if we have a filled in code_postal and no postal_code from la BAN but a insee code, consider the filled in code_postal as valid :finger_crossed:

Fix BAN not returning postal_code for TOM

---

Procfile

Celery will end up using some swap add taking more memory than needed. Start with 500 and we will monitor it.
https://docs.celeryq.dev/en/latest/userguide/workers.html#max-tasks-per-child-setting

Reboot Celery workers once in a while

---

erp/exceptions.py
erp/management/commands/remove_duplicate_mairie.py
tests/erp/test_commands.py

This change will lead to the number of "unhandled" cases to be falsy in dry mode because all the ERPs will be counted (see test).
As we are no longer sure that we keep the ERP coming from service public we need to copy the ASP Id when it exists.

Adapt command to remove duplicates for town halls

---

erp/management/commands/update_geometry.py
tests/erp/test_command_update_geometry.py

Add a command to update the geometry and the contours of the Commune object (municipalities).
This command takes about an hour or so due to the number of API calls.

Add command to update geometry of Commune

---

erp/managers.py
tests/erp/test_managers.py

Fix the having label manager method, this will fix the corresponding having label filter in the search (and in the API).
The case that was not handled is when the labels array is set to an empty list ([]). This situation was not excluded by the "isnull" clause. Switch to using the length of the array and add tests.

Fix the "having label" filter

---

compte/service.py
compte/signals.py
erp/models.py
erp/views.py
tests/erp/test_browser.py

When following the nominal sign up funnel, while creating an ERP, the ERP is first created with no user, then the user is created and associated to the ERP. In that case we were not synch'ing user to Brevo as we were only synch'ing user when ERP is created.

Always sync user to Brevo

---

erp/management/commands/import_laposte.py
tests/erp/imports/test_import_laposte.py

The comment attribute is limited to 1000 char. Adjust sentences to reduce the global comment length

Adjust sentence to reduce comment length

---

templates/contrib/7-commentaire.html

Make sure we ask the question on the "type de handicap" only when the "Tourisme et Handicap" label is checked. This question does not make any sense for the other labels.

Fix question display in contribution step

---

templates/stats/index.html

We now use stats.beta to display the graph on the stats page.

Switch matomo graph to new server

---

erp/provider/generic_geoloc.py

At this point we don't want to autocomplete an address, we have the complete one.
This param enhance the scoring, don't ask me why.
The default value is autocomplete=1, we only want it on client side, it is done in the `api.js` file.

Use autocomplete=0 on BAN API.

---

erp/admin.py

When manually managing SP duplicates, we need to edit this asp_id.

Be able to edit asp_id

---

erp/export/static/schema.json
erp/models.py
erp/schema.py
erp/templatetags/a4a.py
erp/views.py
locale/en/LC_MESSAGES/django.po
locale/fr/LC_MESSAGES/django.po
templates/erp/includes/access_accommodation.html
templates/erp/includes/access_entrance.html
templates/erp/includes/access_legal.html
templates/erp/includes/access_outside_path.html
templates/erp/includes/access_parking.html
templates/erp/includes/access_reception.html
templates/erp/includes/access_stairs.html
templates/erp/includes/access_steps.html
templates/erp/includes/access_value.html
templates/erp/index.html

Add a new way of displaying the accessbility data on the ERP details page to try and make it more readable.
The main change we have here is that we stop considering that the way we store the data is the same way we should display the data to the end user.
Now some bullet points are a built by adding the information of one, two or three fields in the database. This is an attempt to improve the readability of the accessbility data.

Introduce new display of access data on ERP detail

---

erp/templatetags/a4a.py
locale/en/LC_MESSAGES/django.po
locale/fr/LC_MESSAGES/django.po
static/scss/style.scss
templates/erp/includes/access_accommodation.html
templates/erp/includes/access_entrance.html
templates/erp/includes/access_outside_path.html
templates/erp/includes/access_parking.html
templates/erp/includes/access_reception.html
templates/erp/includes/access_steps.html
templates/erp/includes/access_value.html
templates/erp/index.html

The None values where not handled correctly in most of the places, this commit tries to fix this.
I also fixed the fact that we could display title when the section was empty. I could not do it inside the view (we do not know what we are going to display) and did not wanted to it in Js.
If the `:empty` selector was handled correctly in the browsers with CSS4 selectors we could have use it directly but I had to remove all the spaces with the `spaceless` template tag to clean the HTML.
https://developer.mozilla.org/fr/docs/Web/CSS/:empty

Handle None values in new ERP display

---

erp/models.py
templates/erp/includes/access_entrance.html

Show the verbose text instead of the database value for `entree_dispositif_appel_type`. This makes the display more explicit.

Show verbose text for dispositif appel type

---

erp/models.py
tests/erp/test_models.py

Make sure always return a value for steps direction even when the number of steps is not known.

Fix helper function when unknown value

---

erp/templatetags/a4a.py
static/index.js
static/js/ui/FilterData.js
static/js/ui/LabelTag.js
static/js/ui/index.js
templates/erp/includes/access_accommodation.html
templates/erp/includes/access_comment.html
templates/erp/includes/access_entrance.html
templates/erp/includes/access_legal.html
templates/erp/includes/access_outside_path.html
templates/erp/includes/access_parking.html
templates/erp/includes/access_reception.html
templates/erp/includes/access_steps.html
templates/erp/includes/access_value.html
templates/erp/includes/filters.html
templates/erp/index.html
templates/search/tag_with_label.html

Add the possibility for the user to filter on one or multiple types of handicap. By doing so we only display the data we think is appropriate for this type of handicap.
- Re-use tag_with_label.html which was not used in the code
- Implement filters with icons and JavaScript logic
- Add the type of handicap on all the data of the page (all the <li> tags)

Add filters on ERP detail page

---

static/js/widget.js
templates/erp/widget/index.html

It looks like the content of the widget was not read by screen readers,
this commits tries to fix this.
All my tests were done using Orca and Chromium, for both a classic
widget and a "controlled" widget. For each test I tried to read the
heading (shortcut `h` for Orca) and the content of the modal (down arrow
to read line per line using Orca).
The main problem this commits fixes is that all the content of the
widget was inside a div with the `aria-hidden` set to true, even if the
content itself (nested inside this div) had `aria-hidden`set to false,
it looks like screen-readers won't consider the content in this case.
I did not found a clear answer on whether nested `aria-hidden` are valid
or not, but considered it is probably a bad idea anyway. Using my test
setup (I guess support can …

Improve accessibility of widget for screen readers

---

core/lib/text.py
erp/models.py
erp/views.py
tests/erp/test_browser.py

Create a revision when a user confirms ERP is up to date via the up to date button on the ERP page.
- Move the logic to the model to make sure is can be re-used
- Adapt the logic of the _get_history function. Some fields where not displayed because the type was not handle in the text library. I had to add the datetime type and added the other datetime to the exclude_fields parameter to make sure we dont see updated_at in the history
- Add check for the number of revisions in the test

Create revision when a user confirms ERP

---

erp/management/commands/start_scheduler.py
erp/views.py
stats/management/commands/refresh_stats.py
stats/models.py
stats/queries.py
templates/challenge/detail_v2.html
tests/stats/test_challenges.py

Implement incremental computation for the challenges' scores. Compute figures for day D-1, daily.
I am a firefighter, so don't blame me :pray: . This code is far from perfect, and the initial model structure, along with maintaining two versions, doesn't help matters.
Currently, in prod, the refresh_stats for the DDT DEAL 2024 challenge is taking approximately 40 minutes to compute all scores (started ~17 days ago).
In `classement` and `classement_team` we are now storing a indexed by day structure. Every day we append the computation for day D-1.
getters have been implemented to keep the old structure we had and to perform a sort by score.

Implement incremental challenge scores computation.

---

compte/management/commands/purge_obsolete_objects_in_base.py

In future, we could probably purge challenge players, but ATM we cannot delete users who are member of a challenge (even if it is a closed challenge) (cascade protection).

Do not try to purge users if they are member of a challenge.

---

static/js/ui/FilterData.js

The `has(+ ul:empty)` CSS rule is not handled properly on old browsers (including those used in the french administration) so we are adding this JavaScript logic to hide the title when needed. I am also leaving the CSS rule is anyone don't want to use the JavaScript but has a decent browser.

Hide empty section on ERP page for old browsers

---

erp/models.py
locale/en/LC_MESSAGES/django.po
locale/fr/LC_MESSAGES/django.po
templates/erp/includes/labels.html
templates/erp/index.html

- Don't show the "Autres" if we don't have the name of the label
- When we have the name, don't try to show an image

Improve label display for "Autres" labels

---

templates/common/sentry.html

This commit will fix our frontend integration with Sentry. This was not spotted earlier as Sentry is not used for local env.
I am not sure when this issue was introduced but I made the changes following the releases notes of the version 8.0.0. I also used the documentation as an extra reference to make sure this change was intended. This was also documented in the migration guide.
https://github.com/getsentry/sentry-javascript/releases/tag/8.0.0
https://docs.sentry.io/platforms/javascript/performance/#configure https://github.com/getsentry/sentry-javascript/blob/8.0.0/MIGRATION.md#removal-of-class-based-integrations

Fix issue with Sentry initialization

---

erp/views.py

Check that the referer is on our site before redirecting.

Mitigate redirect to referer security alert.

---

core/settings.py

With the introduction of CSP the Django Admin of the ERPs was not loading properly anymore. This is due to `GeoModelAdmin` loading a JavaScript file from Cloudflare (see `openlayers_url`).
From there I had 3 options:
- Self host the JS file and override the class. I did not choose this option as it will make the maintenance of this code very hard. The admin could break any time and we will need to update the JS file manualy.
- Add the `cdnjs.cloudflare.com` domain to the allowed CSP list, which seems dangerous as it is very easy to updload a file that could be dangereous on this domain.
- Disable the CSP on the Django admin. I picked this option, the probability of having a XSS in the admin is pretty low and the attack would be very hard (few people have access to the admin, hard for the …

Add Django admin to CSP_EXCLUDE_URL_PREFIXES

---

Pipfile
Pipfile.lock

In dev env, colorama comes with djlint, but as it is a dev dep, we do not have colorama on prod (but we used to have it, trough an other dep I guess). Bring back colorama as a prod dep.

Add colorama to deps.

---

erp/forms.py

Make sure we make the link in the warning box more visible when an ERP already exists.

Make link in warning more visible

---

locale/en/LC_MESSAGES/django.po
locale/fr/LC_MESSAGES/django.po
static/scss/style.scss
templates/contrib/includes/nav.html
templates/erp/includes/versions_block.html
templates/erp/includes/widget_block.html
templates/index.html

- Fix copy paste for widget code (due to migration to BS5)
- add a hover on all buttons to have consistency between link and buttons, especially on ERP detail page.
- Small work on css class, avoid spaces if no class added
- fix `Désabonnez`

CSS fixes on contrib, button, erp detail view.

---

compte/management/commands/sync_brevo.py

When updating an existing ERP during import process, we won't set/change the source, so we should not rely on it for the sync

Remove source filter in ERP sync

---

compte/views.py
templates/compte/mes_challenges.html

Loop over challenge subscriptions instead of challenges. The way it was done, we were unable to easily get the subscription date per challenge.

Fix non sense subscription date.

---

api/filters.py
erp/managers.py
erp/views.py
static/js/geo.js
templates/common/map.html
tests/api/tests.py

Change ordering of the API when looking for a specific city or department. The ERPs coming from the exact location will be first.
Try to simplify the parameters of the geo.js file to make sure we don't have to pass parameters in all the functions.

Change ordering when looking for a specific place

---

static/js/geo.js

The last refacto has introduced a bug managing GET parameters, especially `equipments` which has to be a list of GET parameters : `...?equiments[]=having_wc&equipments[]=having_parking&...`

Fix equipments filter

---

core/settings_dev.py
erp/views.py
tests/erp/test_browser.py

Fixes [https://github.com/MTES-MCT/acceslibre/security/code-scanning/57](https://github.com/MTES-MCT/acceslibre/security/code-scanning/57)
To fix the problem, we need to ensure that the user-provided query parameters do not lead to an open redirect vulnerability. We can use Django's `url_has_allowed_host_and_scheme` function to validate the constructed URL before redirecting. This function checks that the URL is safe by ensuring it does not contain an untrusted host or scheme.
1. Import the `url_has_allowed_host_and_scheme` function from `django.utils.http`.
2. Validate the `search_url` before redirecting.
3. If the URL is not valid, redirect to a safe default URL (e.g., the home page).
_Suggested fixes powered by Copilot Autofix. Review carefully before merging._

Fix code scanning alert no. 57: URL redirection from remote source

---

erp/management/commands/cancel_user_modifications.py
erp/models.py
tests/erp/test_cancel_user_modifications.py
tests/subscription/test_commands.py

Add a command to revert the changes made by one user if:
- The ERP was not "confirmed up to date" in the meantine
- No other revision more recently

Allow to revert changes made by one user

---

erp/management/commands/cancel_user_modifications.py

The target version may be obsolete, non-compliant with the current data model, and therefore not reversible.
Additionally, the absence of consistency checks in the old version could be another reason why reverting to it is not possible.
These cases should be ignored.

Manage non reversible versions.

---

erp/forms.py
tests/erp/test_browser.py

Previously the profanity check was done during the form.is_valid() call, but at this point the user can be non authenticated. Move the profanity check to the save() method, after a potential redirection to the login form, so that the user is always authenticated on save().

Fix profanity check for not authenticated user

---

core/settings.py

Adding a connect_src was breaking the fallback on default_src.

Use default policy

---

erp/utils.py
static/js/geo.js

Not the best fix ever. Can't find ATM where and when it diverged. From what I can see, the backend is expecting `what` from the beginning, and the frontend is sending `q` from the beginning, but I saw it working :exploding_head:

Fix export params

---

Pipfile
Pipfile.lock

Upgrading to 1.36.x produces
```
Traceback (most recent call last):
File
"/home/mlaure/.local/share/virtualenvs/acceslibre-D3SEUTJ3/lib/python3.12/site-packages/celery/app/trace.py",
line 453, in trace_task
R = retval = fun(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^
File "/home/mlaure/dev/acceslibre/erp/export/tasks.py", line 36, in
generate_csv_file
s3.put_object(Bucket=bucket_name, Key=file_name, Body=csv_buffer.getvalue(),
ContentType="text/csv")
File
"/home/mlaure/.local/share/virtualenvs/acceslibre-D3SEUTJ3/lib/python3.12/site-packages/botocore/client.py",
line 569, in _api_call
return self._make_api_call(operation_name, kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File
"/home/mlaure/.local/share/virtualenvs/acceslibre-D3SEUTJ3/lib/python3.12/site-packages/botocore/client.py",
line …
```

Downgrade boto3

---

static/scss/_leaflet.scss

Leaflet button styles were overridden by the DSFR which caused the button to be transparent when being hovered and focused

[Frontend] Leaflet buttons background-color hover,focus fix

---

erp/views.py
static/js/widget.js
templates/erp/includes/widget_block.html

Some partners have issues integrating the widget because a query selector is too wide and selecting THEIR components instead of ours.
The solution is to add a differentiator such as data-owner="acceslibre" and add this to the selector.
Careful to the retrocompatibility, old scripts still need to work on the partner's end
- https://trello.com/c/c1PJdnnk/2361-pb-li%C3%A9-%C3%A0-laccess-widget

[Frontend] Widget edge case aria-haspopup fix
